solutions = [{
  'name': 'src',
  'url': 'https://chromium.googlesource.com/chromium/src.git',
  'deps_file': '.DEPS.git',
  'managed': False,
  'custom_deps': {
    # Skip syncing some large dependencies WebRTC will never need.
    'src/chrome/tools/test/reference_build/chrome_linux': None,
    'src/chrome/tools/test/reference_build/chrome_mac': None,
    'src/chrome/tools/test/reference_build/chrome_win': None,
    'src/native_client': None,
    'src/third_party/cld_2/src': None,
    'src/third_party/ffmpeg': None,
    'src/third_party/hunspell_dictionaries': None,
    'src/third_party/liblouis/src': None,
    'src/third_party/pdfium': None,
    'src/third_party/skia': None,
    'src/third_party/trace-viewer': None,
    'src/third_party/webrtc': None,
    'src/third_party/WebKit': None,

    # Skip testing by LC
    'src/third_party/android_tools': None, # too big size

    'src/testing/gtest': None,
    'src/breakpad/src': None,
    #'src/buildtools': None,
    'src/sdch/open-vcdiff': None,
    'src/testing/gtest': None,
    'src/testing/gmock': None,
    'src/third_party/angle': None,
    'src/third_party/colorama/src': None,
    'src/third_party/crashpad/crashpad': None,
    #'src/third_party/icu': None,
    'src/third_party/libexif/sources': None,
    'src/third_party/safe_browsing/testing': None,
    'src/third_party/leveldatabase/src': None,
    'src/third_party/snappy/src': None,
    'src/tools/grit': None,
    #'src/tools/gyp': None,
    'src/tools/swarming_client': None,
    'src/v8': None,
    'src/third_party/sfntly/cpp/src': None,
    'src/tools/page_cycler/acid3': None,
    'src/chrome/test/data/perf/canvas_bench': None,
    'src/chrome/test/data/perf/frame_rate/content': None,
    'src/third_party/bidichecker': None,
    'src/third_party/webgl/src': None,
    'src/third_party/webdriver/pylib': None,
    #'src/third_party/libvpx': None,
    'src/third_party/libjingle/source/talk': None,
    #'src/third_party/usrsctp/usrsctplib': None,
    #'src/third_party/libsrtp': None,
    'src/third_party/yasm/source/patched-yasm': None,
    #'src/third_party/libjpeg_turbo': None,
    'src/third_party/flac': None,
    'src/third_party/pyftpdlib/src': None,
    'src/third_party/scons-2.0.1': None,
    #'src/third_party/openmax_dl': None,
    #'src/third_party/jsoncpp/source': None,
    #'src/third_party/libyuv': None,
    'src/third_party/smhasher/src': None,
    'src/third_party/libaddressinput/src': None,

    # These are all at libphonenumber r728.
    'src/third_party/libphonenumber/src/phonenumbers': None,
    'src/third_party/libphonenumber/src/test': None,
    'src/third_party/libphonenumber/src/resources': None,
    'src/tools/deps2git': None,
    'src/third_party/webpagereplay': None,
    'src/third_party/pywebsocket/src': None,
    #'src/third_party/opus/src': None,
    'src/media/cdm/ppapi/api': None,
    'src/third_party/mesa/src': None,
    'src/third_party/libwebm/source': None,

    #'src/third_party/boringssl/src': None,
    'src/third_party/py_trace_event/src': None,
    'src/third_party/dom_distiller_js/dist': None,
    'src/third_party/catapult': None,
  },
  'safesync_url': ''
}]

cache_dir = None
